markdown: kramdown

title: Mathematical scribblings
description: 
google_analytics: true
show_downloads: true
theme: jekyll-theme-merlot
email:   sinahazratpour@gmail.com
facebook: sina.bham
css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

