markdown: kramdown

title: Scribbling
description: maths notes
avatar: https://avatars2.githubusercontent.com/u/12698604?v=3
google_analytics: true
show_downloads: true
email:   sinahazratpour@gmail.com
facebook: sina.bham
github: sinhp/sinhp.github.io.
css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

